### ISSUE TITLE
anti captcha 

### ISSUE THREAD

**Issue by kopkiss** [first130643/Anticapcha-AutoApprove#1]
อันนี้ก้ต้องเสียเงินจ่ายค่า captcha อยุ่ดีใช่มั้ยคับ

**Comment by first130643** [comment]
ใช่ครับ แค่เขียนเพิ่มให้มันกด approve เมื่อแก้เสร็จเฉยๆ
ทดสอบแล้วเสถียรกว่าไปใช้พวกโปรแกรม Autoclick กดแยกครับ ตัดปัญหาจอซ้อน กดไม่ทันเวลาไปได้
